package com.comtrade.enumi;

public enum Konstante {
	
	SACUVAJ_ADRESU,			SACUVAJ_AVIOKOMPANIJU,		SACUVAJ_AVION,			SACUVAJ_AERODROM,		VRATI_LISTU_STATUS_PROFILA,	 		SACUVAJ_PROFIL,
	VRATI_LISTU_ADRESA,		VRATI_LISTU_AVIOKOMPANIJA,	VRATI_LISTU_AVIONA,	 	VRATI_LISTU_AERODROMA,	SACUVAJ_STATUS_PROFILA,	    		VRATI_LISTU_PROFILA,		
	OBRISI_ADRESU,										OBRISI_AVION,			OBRISI_AERODROM,		VRATI_STATUS_ZA_LOGIN,				VRATI_PROFIL_ZA_ID,	
	IZMENI_ADRESU,																															VRATI_PROFIL_ZA_EMAIL,
	VRATI_ADRESU_ZA_ID,																														OBRISI_RPROFIL,
	
	SACUVAJ_RADNIKA,		SACUVAJ_KARAKTERISTIKE_AERODROMA,																				VRATI_PROFIL_ZA_LOGIN,
							VRATI_LISTU_KARAKTERISTIKA_AERODROMA,
							IZMENA_KARAKTERISTIKA_AERODROMA,
	
	MAXIMUM_LETOVA_NA_AERODROMU, 	SACUVAJ_LET,							SACUVAJ_ZAHTEV,
	MAXIMUM_POLETANJA_ZA_DAN,		VRATI_LISTU_LETOVA,						REALIZACIJA_ZAHTEVA,	
	VRATI_BROJ_ZAUZETIH_POLETANJA,	OBRISI_LET,								VRATI_LISTU_AKTIVNIH_ZAHTEVA,
	MAXIMUM_SLETANJA_ZA_DAN,		VRATI_LISTU_LETA_KONKRETNOG_AVIONA,
	VRATI_BROJ_ZAUZETIH_SLETANJA,	PRETRAGA_LET,
	VRATI_LISTU_LETOVA_VREME_DATUM, 	UPISI_CENU_LETA, 
									VRATI_CENU_KLASA_ZA_IZABRANI_LET, 					 SACUVAJ_REZERVACIJU, 	IZMENI_PREOSTALI_BROJ_MESTA, IZMENA_KONTA, VRATI_NAZIV_KOMPANIJE_RADNIKA,  	
									VRATI_LISTU_LETOVA_AVIOKOMPANIJE_ZA_DATUM, 	
									VRATI_LISTU_POVRATNIH_LETOVA_AVIOKOMPANIJE_ZA_DATUM, VRATI_LISTU_REZERVACIJA_ZA_ID, VRATI_LISTU_REZERVACIJA_ZA_ID_LETA, OBRISI_REZERVACIJU, VRATI_LISTU_LETOVA_SA_AERODROMA_ZA_DATUM, VRATI_LISTU_SLETANJA_AERODROM_ZA_DATUM,  
}


